Repository TimerTiTi/TiTi_iOS, pull requests merged in 2024-11, with the labels that each got.

#162 날짜 초기화 자동 프로세스 최종 [Toast 연결]
  Project_Timer.xcodeproj/project.pbxproj
  Project_Timer/Assets.xcassets/calendar.imageset/Contents.json
  Project_Timer/Assets.xcassets/calendar.imageset/calendar 1.svg
  Project_Timer/Assets.xcassets/calendar.imageset/calendar.svg
  Project_Timer/Assets.xcassets/ttPrimary.colorset/Contents.json
  Project_Timer/Base.lproj/Main.storyboard
  Project_Timer/Core/Design System/Theme/Colors.swift
  Project_Timer/Core/Design System/Theme/Fonts.swift
  Project_Timer/Core/Extension/Foundation/Date+Extension.swift
  Project_Timer/Core/Extension/Foundation/Notification+Extension.swift
  Project_Timer/Core/Extension/SwiftUI/View+Extension.swift
  Project_Timer/Core/Extension/UIKit/UIApplication+Extension.swift
  Project_Timer/Core/Extension/UIKit/UIViewController+Extension.swift
  Project_Timer/Core/Global/Protocols.swift
  Project_Timer/Core/Global/SingletonClass/RecordsManager.swift
  Project_Timer/Core/Localize/TLRen.swift
  Project_Timer/Core/Localize/TLRkey.swift
  Project_Timer/Core/Localize/TLRko.swift
  Project_Timer/Core/Localize/TLRzh.swift
  Project_Timer/Core/Resource/Lottie/newRecordLottie.json
  Project_Timer/Core/Resource/Pretendard-Medium.otf
  Project_Timer/Core/Resource/Pretendard-SemiBold.otf
  Project_Timer/Domain/Entity/Daily.swift
  Project_Timer/Domain/UseCase/DailysUseCase.swift
  Project_Timer/Info.plist
  Project_Timer/Present/Stopwatch/StopwatchVC.swift
  Project_Timer/Present/Stopwatch/StopwatchVM.swift
  Project_Timer/Present/Timer/TimerVC.swift
  Project_Timer/Present/Timer/TimerVM.swift
  Project_Timer/Present/ToastMessage/ToastMessage.swift
  Project_Timer/Present/ToastMessage/ToastPresenter.swift
  Project_Timer/Present/ToastMessage/ToastView.swift
  Project_Timer/Present/ToastMessage/newRecordToastView.swift
Labels: feature, pr: needed review

#172 dailys.json 백업 시스템 구축
  Project_Timer/Core/Global/SingletonClass/DailyManager.swift
  Project_Timer/Widget/SharedCode/Storage.swift
Labels: feature, hotfix

#169 feat api error 발생시 loading indicator 제거되도록 수정
  Project_Timer/Core/Design System/Component/View/LoadingIndicator.swift
  Project_Timer/Present/Setting/Service/SettingTiTiLab/TestServer/SyncDailys/SyncDailysVC.swift
  Project_Timer/Present/Setting/Service/SettingTiTiLab/TestServer/SyncDailys/SyncDailysVM.swift
Labels: hotfix
